#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

PROG="/usr/bin/python3"
SCRIPT="/opt/_RunScanner/ap_uploader.py"
NAME="ap-uploader"

start_service() {
    procd_open_instance
    procd_set_param command $PROG $SCRIPT
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    killall -9 python3 2>/dev/null || true
}

reload_service() {
    stop
    start
}
